# Ejercicio 1. 
Escribir un programa que implemente el m´etodo de Jacobi y otro que implemente
el m´etodo de Gauss-Seidel para la resoluci´on de un sistema lineal Ax = b, con las siguientes
condiciones:
• que finalice si el m´etodo se estaciona,
• que finalice con una advertencia si se excede cierto tope de iteraciones.
Sugerencia: investigar los comandos np. tril , np. triu y np.diag.

In [8]:
import numpy as np

#random 3x3 matrix
A = np.random.rand(3,3)
A = np.array([[1, 2, 3], [3, 4, 2], [6, 3, 4]])
A

array([[1, 2, 3],
       [3, 4, 2],
       [6, 3, 4]])

In [5]:
b = [1, 1, 1]
x = np.random.rand(3, 1)
b

array([[0.81527674],
       [0.76480554],
       [0.92559306]])

In [9]:
def jacobi(A, x, b):

    L = np.tril(A,-1)
    D = np.diag(np.diag(A))
    U = np.triu(A,1)

    Bj = -np.linalg.inv(D)@(L+U)
    Cj = np.linalg.inv(D)@ b

    return Bj @ x + Cj

print(x)
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))
print(jacobi(A, x, b))

[[0.84390531]
 [0.18164161]
 [0.15226842]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
[[-0.00481175]
 [-0.51786181]
 [-1.17069091]]
